module JSONInteropTest exposing (suite)

import Dict
import Expect
import Json.Decode as Decode
import Json.Encode as Encode
import Main exposing (..)
import Test exposing (..)


{-| This test ensures that Elm can correctly decode JSON generated by Go
and that Elm generates JSON that Go can decode.
-}
suite : Test
suite =
    describe "JSON Interoperability Tests"
        [ describe "Go -> Elm: Decode Go-generated JSON"
            [ test "ChatItem with type and sender" <|
                \_ ->
                    let
                        json =
                            """{"type":"user","sender":"USER"}"""

                        result =
                            Decode.decodeString chatItemDecoder json
                    in
                    case result of
                        Ok item ->
                            Expect.all
                                [ \_ -> item.type_ |> Expect.equal "user"
                                , \_ -> item.sender |> Expect.equal (Just "USER")
                                , \_ -> item.content |> Expect.equal Nothing
                                , \_ -> item.toolInput |> Expect.equal Nothing
                                ]
                                ()

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ChatItem with content" <|
                \_ ->
                    let
                        json =
                            """{"type":"content","content":"Hello, world!"}"""

                        result =
                            Decode.decodeString chatItemDecoder json
                    in
                    case result of
                        Ok item ->
                            Expect.all
                                [ \_ -> item.type_ |> Expect.equal "content"
                                , \_ -> item.content |> Expect.equal (Just "Hello, world!")
                                , \_ -> item.sender |> Expect.equal Nothing
                                ]
                                ()

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ChatItem permission request" <|
                \_ ->
                    let
                        json =
                            """{"type":"permission_request","sender":"Write","content":"Permission required for Write tool","toolInput":"{\\"file_path\\": \\"/test.txt\\", \\"content\\": \\"test\\"}"}"""

                        result =
                            Decode.decodeString chatItemDecoder json
                    in
                    case result of
                        Ok item ->
                            Expect.all
                                [ \_ -> item.type_ |> Expect.equal "permission_request"
                                , \_ -> item.sender |> Expect.equal (Just "Write")
                                , \_ -> item.content |> Expect.equal (Just "Permission required for Write tool")
                                , \_ -> item.toolInput |> Expect.notEqual Nothing
                                ]
                                ()

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ClaudeMessage with session ID" <|
                \_ ->
                    let
                        json =
                            """{"type":"session","session_id":"test-session-123"}"""

                        result =
                            Decode.decodeString claudeMessageDecoder json
                    in
                    case result of
                        Ok msg ->
                            msg.type_ |> Expect.equal "session"

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ClaudeMessage with assistant text" <|
                \_ ->
                    let
                        json =
                            """{"type":"assistant","message":{"role":"assistant","content":[{"type":"text","text":"I'll help you with that."}]}}"""

                        result =
                            Decode.decodeString claudeMessageDecoder json
                    in
                    case result of
                        Ok msg ->
                            case msg.message of
                                Just messageContent ->
                                    case List.head messageContent.content of
                                        Just content ->
                                            Expect.all
                                                [ \_ -> content.type_ |> Expect.equal "text"
                                                , \_ -> content.text |> Expect.equal (Just "I'll help you with that.")
                                                ]
                                                ()

                                        Nothing ->
                                            Expect.fail "No content in message"

                                Nothing ->
                                    Expect.fail "No message field"

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ClaudeMessage with tool use" <|
                \_ ->
                    let
                        json =
                            """{"type":"assistant","message":{"role":"assistant","content":[{"type":"tool_use","name":"Read","input":{"file_path":"/test/file.go","limit":100},"id":"tool-use-123"}]}}"""

                        result =
                            Decode.decodeString claudeMessageDecoder json
                    in
                    case result of
                        Ok msg ->
                            case msg.message of
                                Just messageContent ->
                                    case List.head messageContent.content of
                                        Just content ->
                                            Expect.all
                                                [ \_ -> content.type_ |> Expect.equal "tool_use"
                                                , \_ -> content.name |> Expect.equal (Just "Read")
                                                , \_ -> content.id |> Expect.equal (Just "tool-use-123")
                                                , \_ -> content.input |> Expect.notEqual Nothing
                                                ]
                                                ()

                                        Nothing ->
                                            Expect.fail "No content in message"

                                Nothing ->
                                    Expect.fail "No message field"

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ClaudeMessage with tool result" <|
                \_ ->
                    let
                        json =
                            """{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"File contents here","tool_use_id":"tool-use-123"}]}}"""

                        result =
                            Decode.decodeString claudeMessageDecoder json
                    in
                    case result of
                        Ok msg ->
                            case msg.message of
                                Just messageContent ->
                                    case List.head messageContent.content of
                                        Just content ->
                                            Expect.all
                                                [ \_ -> content.type_ |> Expect.equal "tool_result"
                                                , \_ -> content.content |> Expect.equal (Just "File contents here")
                                                , \_ -> content.toolUseId |> Expect.equal (Just "tool-use-123")
                                                ]
                                                ()

                                        Nothing ->
                                            Expect.fail "No content in message"

                                Nothing ->
                                    Expect.fail "No message field"

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "ClaudeMessage with error tool result" <|
                \_ ->
                    let
                        json =
                            """{"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"This command requires approval: Write","tool_use_id":"tool-use-456","is_error":true}]}}"""

                        result =
                            Decode.decodeString claudeMessageDecoder json
                    in
                    case result of
                        Ok msg ->
                            case msg.message of
                                Just messageContent ->
                                    case List.head messageContent.content of
                                        Just content ->
                                            Expect.all
                                                [ \_ -> content.type_ |> Expect.equal "tool_result"
                                                , \_ -> content.content |> Expect.equal (Just "This command requires approval: Write")
                                                , \_ -> content.toolUseId |> Expect.equal (Just "tool-use-456")
                                                ]
                                                ()

                                        Nothing ->
                                            Expect.fail "No content in message"

                                Nothing ->
                                    Expect.fail "No message field"

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            ]
        , describe "Elm -> Go: Generate JSON for Go to decode"
            [ test "Generate ChatItem JSON" <|
                \_ ->
                    let
                        items =
                            [ { type_ = "user"
                              , sender = Just "USER"
                              , content = Nothing
                              , toolInput = Nothing
                              }
                            , { type_ = "content"
                              , sender = Nothing
                              , content = Just "Test message"
                              , toolInput = Nothing
                              }
                            , { type_ = "permission_request"
                              , sender = Just "Read"
                              , content = Just "Permission required"
                              , toolInput = Just "{\"file_path\":\"/test.go\"}"
                              }
                            ]

                        encodedItems =
                            List.map encodeChatItem items

                        -- Verify we can round-trip our own encoding
                        results =
                            List.map
                                (\encoded ->
                                    encoded
                                        |> Encode.encode 0
                                        |> Decode.decodeString chatItemDecoder
                                )
                                encodedItems
                    in
                    case results of
                        [ Ok item1, Ok item2, Ok item3 ] ->
                            Expect.all
                                [ \_ -> item1.type_ |> Expect.equal "user"
                                , \_ -> item2.content |> Expect.equal (Just "Test message")
                                , \_ -> item3.sender |> Expect.equal (Just "Read")
                                ]
                                ()

                        _ ->
                            Expect.fail "Failed to round-trip ChatItem encoding"
            , test "Generate Todo JSON" <|
                \_ ->
                    let
                        todos =
                            [ { id = "todo-1"
                              , content = "Implement feature"
                              , status = "in_progress"
                              , priority = "high"
                              , activeForm = Just "Implementing feature"
                              }
                            , { id = "todo-2"
                              , content = "Write tests"
                              , status = "pending"
                              , priority = "medium"
                              , activeForm = Nothing
                              }
                            ]

                        encoded =
                            Encode.list encodeTodo todos

                        -- Verify round-trip
                        result =
                            encoded
                                |> Encode.encode 0
                                |> (\json -> "{\"todos\":" ++ json ++ "}")
                                |> Decode.decodeString todosDecoder
                    in
                    case result of
                        Ok decodedTodos ->
                            Expect.all
                                [ \_ -> List.length decodedTodos |> Expect.equal 2
                                , \_ ->
                                    case decodedTodos of
                                        [ todo1, todo2 ] ->
                                            Expect.all
                                                [ \_ -> todo1.content |> Expect.equal "Implement feature"
                                                , \_ -> todo1.status |> Expect.equal "in_progress"
                                                , \_ -> todo2.content |> Expect.equal "Write tests"
                                                , \_ -> todo2.activeForm |> Expect.equal Nothing
                                                ]
                                                ()

                                        _ ->
                                            Expect.fail "Unexpected number of todos"
                                ]
                                ()

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            ]
        , describe "Edge cases and special characters"
            [ test "Handle escaped quotes in JSON strings" <|
                \_ ->
                    let
                        json =
                            """{"type":"content","content":"He said \\"Hello\\" to me"}"""

                        result =
                            Decode.decodeString chatItemDecoder json
                    in
                    case result of
                        Ok item ->
                            item.content |> Expect.equal (Just "He said \"Hello\" to me")

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "Handle newlines in content" <|
                \_ ->
                    let
                        json =
                            """{"type":"content","content":"Line 1\\nLine 2\\nLine 3"}"""

                        result =
                            Decode.decodeString chatItemDecoder json
                    in
                    case result of
                        Ok item ->
                            item.content |> Expect.equal (Just "Line 1\nLine 2\nLine 3")

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "Handle empty arrays" <|
                \_ ->
                    let
                        json =
                            """{"type":"permission_response","allowedTools":[]}"""

                        result =
                            Decode.decodeString clientMessageDecoder json
                    in
                    case result of
                        Ok msg ->
                            msg.allowedTools |> Expect.equal (Just [])

                        Err err ->
                            Expect.fail (Decode.errorToString err)
            , test "Handle null vs missing fields" <|
                \_ ->
                    let
                        jsonWithNull =
                            """{"type":"content","content":null}"""

                        jsonMissing =
                            """{"type":"content"}"""

                        resultNull =
                            Decode.decodeString chatItemDecoder jsonWithNull

                        resultMissing =
                            Decode.decodeString chatItemDecoder jsonMissing
                    in
                    Expect.all
                        [ \_ ->
                            case resultNull of
                                Ok item ->
                                    item.content |> Expect.equal Nothing

                                Err _ ->
                                    Expect.pass
                        , \_ ->
                            case resultMissing of
                                Ok item ->
                                    item.content |> Expect.equal Nothing

                                Err err ->
                                    Expect.fail (Decode.errorToString err)
                        ]
                        ()
            ]
        ]


-- Helper decoders that might be needed (if not exposed from Main)
chatItemDecoder : Decode.Decoder { type_ : String, sender : Maybe String, content : Maybe String, toolInput : Maybe String }
chatItemDecoder =
    Decode.map4
        (\type_ sender content toolInput ->
            { type_ = type_
            , sender = sender
            , content = content
            , toolInput = toolInput
            }
        )
        (Decode.field "type" Decode.string)
        (Decode.maybe (Decode.field "sender" Decode.string))
        (Decode.maybe (Decode.field "content" Decode.string))
        (Decode.maybe (Decode.field "toolInput" Decode.string))


encodeChatItem : { type_ : String, sender : Maybe String, content : Maybe String, toolInput : Maybe String } -> Encode.Value
encodeChatItem item =
    let
        fields =
            [ ( "type", Encode.string item.type_ ) ]
                ++ (case item.sender of
                        Just s ->
                            [ ( "sender", Encode.string s ) ]

                        Nothing ->
                            []
                   )
                ++ (case item.content of
                        Just c ->
                            [ ( "content", Encode.string c ) ]

                        Nothing ->
                            []
                   )
                ++ (case item.toolInput of
                        Just t ->
                            [ ( "toolInput", Encode.string t ) ]

                        Nothing ->
                            []
                   )
    in
    Encode.object fields


clientMessageDecoder : Decode.Decoder { type_ : String, allowedTools : Maybe (List String) }
clientMessageDecoder =
    Decode.map2
        (\type_ allowedTools ->
            { type_ = type_
            , allowedTools = allowedTools
            }
        )
        (Decode.field "type" Decode.string)
        (Decode.maybe (Decode.field "allowedTools" (Decode.list Decode.string)))