#!/usr/bin/env bash
# GENERATED by distribute-go-bin v0.1.0 -- do not edit.
#
# LOCAL MODIFICATION (re-apply if regenerated): each target's compile is
# preceded by a per-platform `make dockerless-payload` with the other
# platforms' payload dirs pruned, so every published binary embeds exactly
# its own dockerless payload (go:embed picks up whatever dirs exist at
# compile time). A size assertion after each build fails the release if the
# payload is missing. The host payload is restored at the end.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/npm-platforms"
VERSION=$(node -p "require('$REPO_ROOT/package.json').version")
# Honor an explicit COMMIT override (useful when the surrounding shell's
# `git` is wrapped/proxied and `git rev-parse` cannot reach the real repo,
# e.g. inside some sandboxed dev environments). Otherwise, ask git directly.
COMMIT="${COMMIT:-$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")}"
BUILD_TIME="${BUILD_TIME:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"

echo "Building swe-swe v${VERSION} (${COMMIT})"

# -- 1. Cross-compile Go binary for each platform -------------------------
TARGETS=(
  "linux   amd64  linux-x64"
  "linux   arm64  linux-arm64"
  "darwin  amd64  darwin-x64"
  "darwin  arm64  darwin-arm64"
  "windows amd64  win32-x64"
  "windows arm64  win32-arm64"
)

rm -rf "$OUT_DIR"

for target in "${TARGETS[@]}"; do
  read -r goos goarch pkg_suffix <<< "$target"

  pkg_dir="$OUT_DIR/$pkg_suffix"
  bin_dir="$pkg_dir/bin"
  mkdir -p "$bin_dir"

  bin_name="swe-swe"
  if [ "$goos" = "windows" ]; then
    bin_name="swe-swe.exe"
  fi

  # Embed the matching dockerless payload: prune every target's payload dir
  # (keeping bin/.gitkeep), build this platform's, then compile. Without the
  # prune, go:embed would pack every platform's ~43MB into every binary; with
  # no payload at all, `swe-swe init --dockerless` fails at extraction on the
  # user's machine (the 2.29.1 linux-arm64 bug).
  #
  # Windows ships payload-less: swe-swe-server is unix-only (syscall.Kill,
  # Setpgid, SIGUSR1), so a windows payload cannot be built; --dockerless
  # there keeps its clear "payload not built" error. The prune still runs so
  # windows binaries don't embed some other platform's payload.
  rm -rf "$REPO_ROOT/cmd/swe-swe/dockerless-payload/bin"/*-*/
  if [ "$goos" != "windows" ]; then
    echo "-> Building dockerless payload for ${goos}/${goarch}..."
    make -C "$REPO_ROOT" dockerless-payload DOCKERLESS_OS="$goos" DOCKERLESS_ARCH="$goarch" >/dev/null
  fi

  echo "-> Compiling ${goos}/${goarch}..."
  CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" \
    go build -C "$REPO_ROOT" -trimpath -ldflags="-s -w -X main.Version=${VERSION} -X main.GitCommit=${COMMIT} -X main.BuildTime=${BUILD_TIME}" \
    -o "$bin_dir/$bin_name" ./cmd/swe-swe

  # A payload-less binary is ~10MB; with its payload it is ~50MB. Fail the
  # release rather than publish a unix binary that cannot init --dockerless.
  if [ "$goos" != "windows" ]; then
    actual_bytes=$(wc -c < "$bin_dir/$bin_name")
    if [ "$actual_bytes" -lt 40000000 ]; then
      echo "ERROR: $bin_name is ${actual_bytes} bytes -- dockerless payload missing from embed" >&2
      exit 1
    fi
  fi

  # Map goarch to npm cpu field
  case "$goarch" in
    amd64) npm_cpu="x64" ;;
    arm64) npm_cpu="arm64" ;;
  esac

  # Map goos to npm os field
  case "$goos" in
    linux)   npm_os="linux" ;;
    darwin)  npm_os="darwin" ;;
    windows) npm_os="win32" ;;
  esac

  cat > "$pkg_dir/package.json" <<PKGJSON
{
  "name": "@choonkeat/swe-swe-${pkg_suffix}",
  "version": "${VERSION}",
  "description": "swe-swe binary for ${goos}/${goarch}",
  "license": "MIT",
  "os": ["${npm_os}"],
  "cpu": ["${npm_cpu}"],
  "files": ["bin/"]
}
PKGJSON

  echo "  [ok] npm-platforms/${pkg_suffix} ($(du -h "$bin_dir/$bin_name" | cut -f1))"
done

# Leave the tree the way local development expects it: prune the last
# target's payload and rebuild the host-platform one.
rm -rf "$REPO_ROOT/cmd/swe-swe/dockerless-payload/bin"/*-*/
make -C "$REPO_ROOT" dockerless-payload >/dev/null

echo ""
echo "Done. Platform packages are in ${OUT_DIR}/"
ls -1 "$OUT_DIR"
