#!/usr/bin/env bash
# GENERATED by distribute-go-bin v0.1.0 -- do not edit.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT_DIR="$REPO_ROOT/npm-platforms"
DRY_RUN="${DRY_RUN:-true}"
OTP="${NPM_OTP:-}"

# -- 0. Verify optionalDependencies match the main version ----------------
VERSION=$(node -p "require('$REPO_ROOT/package.json').version")
node -e "
  const pkg = require('$REPO_ROOT/package.json');
  const deps = pkg.optionalDependencies || {};
  const bad = Object.entries(deps).filter(([,v]) => v !== pkg.version);
  if (bad.length) {
    bad.forEach(([k,v]) => console.error('  ' + k + ': ' + v + ' (expected ' + pkg.version + ')'));
    process.exit(1);
  }
" || {
  echo ""
  echo "ERROR: optionalDependencies version mismatch!"
  echo "Run: make bump VERSION=$VERSION"
  exit 1
}

if [ "$DRY_RUN" = "true" ]; then
  PUBLISH_ARGS="--dry-run"
  echo "Dry-run mode (set DRY_RUN=false to publish for real)"
else
  PUBLISH_ARGS=""
  if [ -n "$OTP" ]; then
    PUBLISH_ARGS="--otp=$OTP"
  fi
  echo "Publishing for real!"
fi

echo ""

# -- 1. Publish platform packages -----------------------------------------
PLATFORMS=(linux-x64 linux-arm64 darwin-x64 darwin-arm64 win32-x64 win32-arm64)

for platform in "${PLATFORMS[@]}"; do
  pkg_dir="$OUT_DIR/$platform"
  if [ ! -d "$pkg_dir" ]; then
    echo "ERROR: Missing $pkg_dir -- run scripts/build-platforms.sh first"
    exit 1
  fi
  pkg_name="@choonkeat/swe-swe-${platform}"
  # Skip if this exact name@version is already on the registry. Lets the
  # script be re-run safely after a partial publish (e.g. when only the
  # main package failed and the platform packages already shipped).
  if [ "$DRY_RUN" != "true" ] && \
     npm view "${pkg_name}@${VERSION}" version >/dev/null 2>&1; then
    echo "-> Skipping ${pkg_name}@${VERSION} -- already on registry"
    continue
  fi
  echo "-> Publishing ${pkg_name}..."
  npm publish "$pkg_dir" --access public $PUBLISH_ARGS
done

# -- 2. Publish the main package -------------------------------------------
echo "-> Publishing swe-swe..."
npm publish "$REPO_ROOT" --access public $PUBLISH_ARGS

echo ""
echo "Done."
